from dataclasses import dataclass
from typing import Dict, List


@dataclass
class SemanticFieldSet:
    conceptual: List[str]
    operational: List[str]
    narrative: List[str]
    coherence: List[str]
    scientific: List[str]
    legal: list[str]
    business: List[str]

    def as_dict(self) -> Dict[str, List[str]]:
        return {
            "conceptual": self.conceptual,
            "operational": self.operational,
            "narrative": self.narrative,
            "coherence": self.coherence,
            "scientific": self.scientific,
            "legal": self.legal,
            "business": self.business,
        }


DEFAULT_SEMANTIC_FIELDS = SemanticFieldSet(
    conceptual=[
        "Meaning depends on context.",
        "Truth requires coherence.",
        "Identity persists through time.",
        "Contradictions weaken logical systems.",
        "Evidence supports valid conclusions.",
        "Reasoning connects ideas coherently.",
        "Interpretation changes according to perspective.",
        "Concepts gain clarity through definition.",
        "Knowledge depends on justified understanding.",
        "Context determines semantic meaning.",
        "Consistency strengthens rational arguments.",
        "Logic establishes valid relationships.",
        "Existence precedes interpretation.",
        "Truth corresponds to reality.",
        "Understanding requires contextual awareness.",
        "Language expresses abstract concepts.",
        "Meaning emerges from relationships.",
        "Identity allows recognition over time.",
        "Reason organizes information coherently.",
        "Beliefs should align with evidence.",
        "Definitions reduce semantic ambiguity.",
        "Coherence stabilizes conceptual systems.",
        "Reality can be interpreted through models.",
        "Understanding evolves with knowledge.",
        "Conceptual systems require internal consistency.",
        "Causality connects events meaningfully.",
        "Semantic relations shape interpretation.",
        "Abstractions simplify complex realities.",
        "Ideas interact within conceptual structures.",
        "Logic constrains valid conclusions.",
        "Interpretation depends on prior assumptions.",
        "Truth claims require verification.",
        "Knowledge grows through critical analysis.",
        "Meaningful statements preserve coherence.",
        "Identity distinguishes one entity from another.",
        "Reasoning evaluates relationships between ideas.",
        "Conceptual clarity reduces confusion.",
        "Evidence constrains interpretation.",
        "Contextual stability improves understanding.",
        "Contradictions create semantic instability.",
        "Human understanding depends on language.",
        "Coherent systems resist inconsistency.",
        "Interpretation connects symbols to meaning.",
        "Truth can function as a semantic attractor.",
        "Knowledge requires structured reasoning.",
        "Concepts form networks of relationships.",
        "Meaning is shaped by semantic context.",
        "Logical consistency supports comprehension.",
        "Context filters relevant interpretation.",
        "A cause produces an effect.",
        "A system requires structure.",
        "Coherence requires consistency.",
        "Evidence supports a claim.",
        "A contradiction weakens an argument.",
        "Identity allows recognition over time.",
        "A relation connects two or more things.",
        "Interpretation depends on context.",
        "Truth requires correspondence or coherence.",
    ],
    operational=[
        "Water boils at 100 degrees Celsius.",
        "Paris is the capital of France.",
        "database stores customer records.",
        "server processes incoming requests.",
        "invoice was approved yesterday.",
        "network connection is stable.",
        "system generated a monthly report.",
        "company issued a purchase order.",
        "process requires user authentication.",
        "customer completed the transaction.",
        "Mexico has 32 federal entities.",
        "application uses encrypted communication.",
        "warehouse contains operational inventory.",
        "backup completed successfully.",
        "payment was processed by the bank.",
        "router distributes network traffic.",
        "temperature sensor detected overheating.",
        "software updates automatically every night.",
        "employee submitted the financial report.",
        "airport handles international flights.",
        "contract expires next year.",
        "container arrived at the port.",
        "invoice includes applicable taxes.",
        "operating system manages hardware resources.",
        "machine requires scheduled maintenance.",
        "hospital stores medical records securely.",
        "firewall blocks unauthorized access.",
        "logistics team confirmed the shipment.",
        "system administrator reset the password.",
        "bank approved the loan request.",
        "company tracks operational expenses.",
        "application stores data in the cloud.",
        "meeting starts at nine o'clock.",
        "engineer repaired the damaged server.",
        "customer received the confirmation email.",
        "sensor measures atmospheric pressure.",
        "transaction history is stored in the database.",
        "printer is connected to the local network.",
        "software license expires in December.",
        "report contains quarterly sales figures.",
        "organization follows security protocols.",
        "package was delivered this morning.",
        "technician installed the new hardware.",
        "accounting department verified the balance.",
        "internet service is temporarily unavailable.",
        "company increased production capacity.",
        "user uploaded the requested document.",
        "server room requires climate control.",
        "operational process includes quality verification.",
        "system detected unusual activity.",
        "Water boils at a measurable temperature.",
        "Earth orbits the Sun.",
        "Moon orbits the Earth.",
        "Plants need sunlight to grow.",
        "Humans need oxygen to survive.",
        "A dog is an animal.",
        "A car uses wheels to move.",
        "Temperature can be measured in degrees.",
        "Rain can make the ground wet.",
    ],
        narrative=[
        "knight faced the dragon at dawn.",
        "A mysterious traveler entered the ancient city.",
        "princess discovered a hidden passage beneath the castle.",
        "detective followed the final clue through the rain.",
        "hero returned home after the long journey.",
        "A shadow moved silently across the empty street.",
        "old king guarded a dangerous secret.",
        "child opened a door to another world.",
        "warrior carried the map through the desert.",
        "storm surrounded the abandoned lighthouse.",
        "captain led the crew into unknown waters.",
        "storyteller described a forgotten civilization.",
        "scientist realized the experiment had awakened something alive.",
        "village celebrated the return of the lost explorer.",
        "assassin disappeared into the crowded market.",
        "young programmer uncovered a dangerous conspiracy.",
        "queen listened carefully to the prophecy.",
        "stranger arrived carrying a mysterious artifact.",
        "rebel group planned their escape at midnight.",
        "forest seemed alive with whispers.",
        "astronaut watched Earth disappear into darkness.",
        "soldier remembered the final moments of the battle.",
        "dragon slept beneath the mountain.",
        "musician played a melody no one had heard before.",
        "traveler searched for meaning across distant lands.",
        "ancient book revealed a forgotten truth.",
        "city lights reflected across the river at night.",
        "inventor created a machine capable of changing history.",
        "family gathered around the fire during the storm.",
        "detective realized the witness was lying.",
        "prisoner escaped before sunrise.",
        "explorer entered the ruins despite the warnings.",
        "ship vanished into the fog without explanation.",
        "mentor guided the student through difficult trials.",
        "guardian protected the sacred temple.",
        "boy dreamed of flying beyond the stars.",
        "journalist uncovered corruption inside the corporation.",
        "hunter followed footprints through the snow.",
        "artist painted visions of another reality.",
        "king feared the return of the enemy army.",
        "scientist warned the team about the unstable reactor.",
        "orphan discovered an unusual power within herself.",
        "rebels transmitted a secret message at dawn.",
        "woman waited at the station for someone who never arrived.",
        "castle stood abandoned after the war.",
        "crew heard strange sounds below the ship.",
        "traveler crossed the bridge into the silent city.",
        "librarian protected documents hidden for centuries.",
        "final letter changed everything the family believed.",
        "machine continued operating after everyone had disappeared.",
        "dragon guarded the ancient kingdom.",
        "A wizard opened the gate with a spell.",
        "hero crossed the dark forest.",
        "queen protected the hidden city.",
        "A knight carried the sword of light.",
        "child found a door beneath the mountain.",
        "old map revealed a forgotten island.",
        "monster slept under the bridge.",
        "travelers followed the river to the castle.",
        "curse ended when the bell rang.",
    ],
        coherence=[
        "A statement cannot be both true and false in the same context.",
        "A coherent system preserves internal consistency.",
        "Contradictions weaken semantic stability.",
        "A cause precedes its effect.",
        "An object remains identical to itself within the same reference.",
        "A valid explanation maintains logical continuity.",
        "A coherent argument does not deny its own premises.",
        "Meaningful systems preserve relational consistency.",
        "Identity persists across coherent interpretation.",
        "A statement should not affirm and deny the same thing simultaneously.",
        "Logical consistency supports semantic stability.",
        "A coherent structure preserves compatible relations.",
        "An effect cannot occur before its cause within the same timeline.",
        "A valid interpretation maintains contextual continuity.",
        "Semantic coherence reduces contradiction.",
        "Stable systems preserve compatible meanings.",
        "A coherent statement maintains reference integrity.",
        "Internal consistency strengthens understanding.",
        "Contradictory premises generate instability.",
        "A coherent explanation preserves causal order.",
        "A thing cannot simultaneously exist and not exist in the same context.",
        "Logical compatibility supports coherent reasoning.",
        "Stable interpretations avoid self-contradiction.",
        "A coherent model preserves relational order.",
        "Consistency stabilizes semantic structures.",
        "A valid conclusion follows from its premises.",
        "A coherent narrative preserves temporal continuity.",
        "An entity cannot be larger and smaller than itself in the same sense.",
        "Coherence requires compatible relations between concepts.",
        "A stable system maintains interpretive continuity.",
        "A contradiction disrupts contextual stability.",
        "Semantic consistency strengthens comprehension.",
        "A coherent framework preserves internal alignment.",
        "Identity cannot simultaneously collapse and persist within the same reference.",
        "Stable reasoning preserves logical continuity.",
        "A coherent system avoids incompatible states.",
        "A semantic structure requires relational compatibility.",
        "Temporal order supports coherent interpretation.",
        "Meaningful relations preserve structural stability.",
        "A coherent context maintains compatible references.",
        "Logical coherence constrains interpretation.",
        "Stable concepts preserve recognizable identity.",
        "A coherent explanation avoids impossible causality.",
        "Semantic instability emerges from contradiction.",
        "A coherent structure preserves valid dependencies.",
        "Contradictions increase interpretive instability.",
        "A meaningful system maintains internal order.",
        "Consistency supports reliable interpretation.",
        "A coherent semantic field preserves compatible meanings.",
        "Structural coherence stabilizes contextual understanding.",
        "A statement cannot be both true and false in the same context.",
        "A coherent statement does not contradict itself.",
        "Contradiction invalidates internal coherence.",
        "A consistent claim does not affirm and deny the same thing.",
        "Truth and falsehood cannot apply simultaneously in the same reference.",
        "An object cannot be entirely present and entirely absent at the same time.",
        "A cause cannot depend on its own future effect.",
        "A thing cannot be identical and not identical to itself in the same context.",
    ],
        scientific=[
        "Scientific knowledge depends on empirical observation.",
        "Experiments test hypotheses under controlled conditions.",
        "Evidence supports or refutes scientific models.",
        "Measurement improves the precision of observations.",
        "Gravity influences the motion of massive objects.",
        "Energy cannot be created or destroyed in an isolated system.",
        "Cells are the basic units of life.",
        "Chemical reactions involve molecular transformations.",
        "Temperature affects the behavior of matter.",
        "Mass influences gravitational interaction.",
        "The Earth orbits the Sun due to gravitational attraction.",
        "Water changes state depending on temperature and pressure.",
        "DNA contains genetic information.",
        "Evolution explains biological adaptation over time.",
        "Atoms are composed of subatomic particles.",
        "Light behaves as both a wave and a particle.",
        "Scientific theories organize observable phenomena.",
        "A valid experiment should be reproducible.",
        "Data analysis reveals measurable patterns.",
        "Scientific models approximate reality.",
        "Evidence-based reasoning strengthens scientific conclusions.",
        "Observations require consistent measurement methods.",
        "A hypothesis should generate testable predictions.",
        "Variables influence experimental outcomes.",
        "Scientific explanations depend on causal relationships.",
        "The microscope revealed cellular structures.",
        "The analysis detected statistical correlation.",
        "Researchers measured atmospheric pressure variations.",
        "The experiment demonstrated energy transfer.",
        "The sensor recorded temperature fluctuations.",
        "The laboratory verified the chemical composition.",
        "Data indicates a significant increase in velocity.",
        "The telescope detected distant galaxies.",
        "Researchers observed unusual electromagnetic activity.",
        "The results support the original hypothesis.",
        "Scientists analyzed molecular interactions.",
        "The sample was examined under controlled conditions.",
        "The calculation predicts orbital behavior.",
        "The equation models population growth.",
        "The experiment failed to confirm the prediction.",
        "Scientific progress depends on verification and revision.",
        "A controlled environment reduces experimental noise.",
        "Statistical analysis estimates probability distributions.",
        "Scientific reasoning seeks coherent explanations.",
        "Radiation can alter biological tissue.",
        "The study evaluated the effectiveness of the treatment.",
        "The reaction released thermal energy.",
        "The instrument detected seismic activity.",
        "Peer review evaluates scientific validity.",
        "Scientific understanding evolves through evidence."
    ],
        legal=[
        "Laws regulate the behavior of individuals and institutions.",
        "Contracts establish legally binding obligations.",
        "Courts interpret and apply legal principles.",
        "A valid agreement requires mutual consent.",
        "Evidence supports legal arguments in judicial proceedings.",
        "The constitution defines the structure of government authority.",
        "Legal responsibility depends on applicable law.",
        "Judges evaluate facts according to legal standards.",
        "A criminal offense violates established law.",
        "Civil disputes involve competing legal claims.",
        "A witness provides testimony under oath.",
        "Legal systems establish procedures for resolving conflicts.",
        "A valid contract requires identifiable parties.",
        "The defendant has the right to legal representation.",
        "Regulations govern administrative procedures.",
        "Property rights protect lawful ownership.",
        "The prosecution must prove guilt beyond reasonable doubt.",
        "Legal interpretation depends on statutory language.",
        "A lawsuit may involve financial damages.",
        "Judicial decisions establish legal precedent.",
        "The court reviewed the submitted evidence.",
        "The attorney filed a motion before the hearing.",
        "The judge issued a temporary injunction.",
        "The agreement was signed by both parties.",
        "The defendant denied the allegations in court.",
        "The investigation revealed procedural violations.",
        "The witness described the sequence of events.",
        "The contract established payment obligations.",
        "The ruling interpreted constitutional authority.",
        "The law prohibits fraudulent financial activity.",
        "The plaintiff requested compensation for damages.",
        "The appeal challenged the lower court decision.",
        "The legal process requires documented evidence.",
        "The regulation establishes compliance standards.",
        "The hearing examined conflicting testimony.",
        "The prosecutor presented forensic evidence.",
        "The court evaluated the credibility of witnesses.",
        "The legal framework defines institutional authority.",
        "The statute regulates commercial transactions.",
        "The agreement included confidentiality provisions.",
        "The legal claim depended on contractual interpretation.",
        "The investigation examined digital evidence.",
        "The court determined that the procedure was unlawful.",
        "Legal analysis requires interpretation of applicable statutes.",
        "The legislation introduced new compliance requirements.",
        "The attorney negotiated a settlement agreement.",
        "The judicial system guarantees procedural rights.",
        "The contract specified liability limitations.",
        "The ruling established a binding precedent.",
        "Legal reasoning depends on coherent interpretation of law."
    ],
        business=[
        "Business strategy defines organizational direction.",
        "Companies create value through products and services.",
        "Revenue measures income generated by business activity.",
        "Profit depends on revenue, costs, and operational efficiency.",
        "Market demand influences business decisions.",
        "Customers evaluate value before purchasing a product.",
        "Organizations allocate resources to achieve strategic goals.",
        "A business model explains how a company creates and captures value.",
        "Leadership guides teams toward shared objectives.",
        "Operational efficiency improves business performance.",
        "Financial reports summarize organizational performance.",
        "Sales growth reflects market traction.",
        "Customer satisfaction influences long-term retention.",
        "A company tracks key performance indicators.",
        "Business decisions depend on available data.",
        "Marketing communicates value to potential customers.",
        "A competitive advantage differentiates a company from rivals.",
        "Strategic planning aligns resources with goals.",
        "The management team reviewed quarterly results.",
        "The company expanded into a new market.",
        "The sales department increased monthly revenue.",
        "The board approved the annual budget.",
        "The organization improved internal processes.",
        "The customer success team reduced churn.",
        "The finance department analyzed operating expenses.",
        "The company launched a new product line.",
        "The executive team evaluated market risks.",
        "The business unit reported higher profit margins.",
        "The company negotiated a partnership agreement.",
        "The operations team optimized the supply chain.",
        "The marketing campaign increased brand awareness.",
        "The company improved customer acquisition.",
        "The leadership team defined strategic priorities.",
        "The organization measured employee productivity.",
        "The company adjusted pricing based on demand.",
        "The business report identified growth opportunities.",
        "The executive committee evaluated investment options.",
        "The company reduced costs through automation.",
        "The sales forecast projected higher demand.",
        "The organization improved decision-making with analytics.",
        "The company evaluated customer lifetime value.",
        "The business strategy focused on sustainable growth.",
        "The company managed risk through internal controls.",
        "The team aligned operational goals with financial targets.",
        "The company reviewed performance against annual objectives.",
        "The organization created a plan for market expansion.",
        "The business process improved delivery times.",
        "The company analyzed revenue trends across regions.",
        "The leadership team communicated the strategic vision.",
        "The organization balanced growth, risk, and profitability."
    ],
)