FACTUAL_PROTOTYPES = {

    "PhysicalReality": [
        "Physical objects occupy space and time",
        "Material bodies exist in the observable world",
        "Objects move and interact in physical reality",
        "Matter has extension and location",
        "A body can change position over time",
        "Physical events occur in the world",
        "Material systems can be observed directly",
        "Objects can collide and exert force",
        "Los objetos físicos existen en el espacio y el tiempo",
        "Los eventos materiales ocurren en el mundo observable",
        "Los cuerpos ocupan lugar y cambian con el tiempo",
        "La materia puede observarse y medirse",
        "Un objeto físico puede moverse",
        "Los cuerpos interactúan en el mundo material",
        "La realidad física contiene objetos y procesos"
    ],

    "Measurement": [
        "Quantities can be measured under defined conditions",
        "Temperature can be measured in degrees Celsius",
        "Mass can be measured in kilograms",
        "Distance can be measured in meters",
        "Time can be measured in seconds",
        "Pressure can be measured in pascals",
        "Volume can be measured in liters",
        "Length can be measured with standard units",
        "Speed is measured as distance over time",
        "Scientific measurement depends on units and conditions",
        "Las magnitudes pueden medirse bajo condiciones definidas",
        "La temperatura puede medirse en grados Celsius",
        "La masa puede medirse en kilogramos",
        "La distancia puede medirse en metros",
        "La presión puede medirse con unidades definidas"
    ],

    "Geography": [
        "Cities belong to countries and regions",
        "A capital city is a political and geographic designation",
        "Countries contain cities, borders, and territories",
        "Geographic facts relate places to territories",
        "Paris is a city in France",
        "France is a country in Europe",
        "Tokyo is a city in Japan",
        "Mexico City is the capital of Mexico",
        "Berlin is the capital of Germany",
        "Brazil is a country in South America",
        "The Nile is a river in Africa",
        "Mount Everest is located in Asia",
        "Las ciudades pertenecen a países y regiones",
        "Una capital es una designación política y geográfica",
        "Los hechos geográficos relacionan lugares con territorios"
    ],

    "Astronomy": [
        "Planets orbit stars under gravitational relations",
        "The Earth moves around the Sun",
        "The Moon orbits the Earth",
        "Mars is a planet in the solar system",
        "The Sun is a star",
        "Stars produce light and heat",
        "Celestial bodies follow observable astronomical patterns",
        "The solar system contains planets and moons",
        "Gravity influences orbital motion",
        "Astronomical objects can be observed in space",
        "Los planetas orbitan estrellas",
        "La Tierra gira alrededor del Sol",
        "La Luna orbita la Tierra",
        "Los cuerpos celestes siguen patrones observables",
        "La gravedad influye en el movimiento orbital"
    ],

    "ScientificRegularity": [
        "Physical systems exhibit regular behavior under stable conditions",
        "Water freezes near 0 degrees Celsius under standard pressure",
        "Water boils near 100 degrees Celsius at sea level",
        "Objects fall due to gravity",
        "Heat increases molecular motion",
        "Pressure affects boiling point",
        "Empirical laws describe repeatable patterns in nature",
        "Metals expand when heated",
        "Light travels at a finite speed",
        "Energy is conserved in closed systems",
        "Regularities in nature can be described scientifically",
        "Los sistemas físicos muestran regularidades bajo condiciones estables",
        "El agua cambia de estado según temperatura y presión",
        "La gravedad produce caída de los cuerpos",
        "Las leyes empíricas describen patrones repetibles"
    ],

    "EmpiricalVerification": [
        "A factual claim can be checked against observation or measurement",
        "Empirical verification compares statements with evidence",
        "Observations support or refute factual propositions",
        "Evidence can confirm or disconfirm a claim",
        "Scientific claims require observable support",
        "Measurements can test a hypothesis",
        "Observation is used to verify empirical statements",
        "Facts can be contrasted with evidence",
        "Repeatable observation strengthens empirical support",
        "Verification depends on comparison with reality",
        "Una afirmación factual puede verificarse con evidencia",
        "La observación permite contrastar proposiciones empíricas",
        "La evidencia puede confirmar o refutar una afirmación",
        "Las mediciones permiten probar hipótesis",
        "La verificación empírica compara lenguaje con observación"
    ],

    "NamedEntityFacts": [
        "Paris is the capital of France",
        "Berlin is the capital of Germany",
        "Tokyo is the capital of Japan",
        "Madrid is the capital of Spain",
        "Rome is the capital of Italy",
        "Ottawa is the capital of Canada",
        "Canberra is the capital of Australia",
        "The Earth orbits the Sun",
        "The Moon orbits the Earth",
        "The Pacific Ocean is the largest ocean on Earth",
        "Mount Everest is the highest mountain above sea level",
        "The Nile is one of the longest rivers in the world",
        "La Ciudad de México es la capital de México",
        "París es la capital de Francia",
        "Tokio es la capital de Japón"
    ],

    "ExperimentalConditions": [
        "Water boils near 100 degrees Celsius at sea level",
        "Water freezes near 0 degrees Celsius under standard pressure",
        "Boiling point changes with atmospheric pressure",
        "At higher altitude water boils at a lower temperature",
        "Temperature measurements depend on environmental conditions",
        "Pressure influences phase transitions",
        "Experimental results depend on controlled conditions",
        "A physical measurement requires specified conditions",
        "Scientific observations must state relevant conditions",
        "State changes depend on temperature and pressure",
        "El agua hierve cerca de 100 grados Celsius al nivel del mar",
        "El punto de ebullición cambia con la presión atmosférica",
        "Los resultados experimentales dependen de condiciones controladas",
        "La presión influye en los cambios de estado",
        "Una medición física requiere condiciones definidas"
    ],
}